version: '3.9'
services:
    postgres_test:
        image: postgres:13
        command: ['-c', 'log_statement=all']
        ports:
            - '2345:5432'
        container_name: car_owner_app_postgres_test
        environment:
            POSTGRES_DB: 'car_owner_app_test'
            POSTGRES_USER: 'car_owner_app_postgres'
            POSTGRES_PASSWORD: 'p0stgr3s'
            POSTGRES_HOST_AUTH_METHOD: 'trust'
