version: '3.9'
services:
    postgres:
        image: postgres:13
        command: ['-c', 'log_statement=all']
        ports:
            - '5432:5432'
        container_name: dev_containers_postgres
        environment:
            POSTGRES_DB: 'dev_containers'
            POSTGRES_USER: 'dev_containers_postgres'
            POSTGRES_PASSWORD: 'p0stgr3s'
            POSTGRES_HOST_AUTH_METHOD: 'trust'
