version: '3.9'
services:
    postgres_test:
        image: postgres:13
        command: ['-c', 'log_statement=all']
        ports:
            - '2345:5432'
        container_name: dev_containers_postgres_test
        environment:
            POSTGRES_DB: 'dev_containers_test'
            POSTGRES_USER: 'dev_containers_postgres'
            POSTGRES_PASSWORD: 'p0stgr3s'
            POSTGRES_HOST_AUTH_METHOD: 'trust'
